### ISSUE TITLE
title page from front matter is ignored in theme

### ISSUE THREAD

**Issue by ousia** [jasonlong/architect-theme#20]
@jasonlong,

generating http://www.escritura-ordenador.tk with Jekyll and GitHub Pages, I get the project title instead of the page title. Title metadata is added in https://raw.githubusercontent.com/ousia/escritura-ordenador/master/README.md.

As far as I know, this should work (per https://jekyllrb.com/docs/frontmatter/).

Am I missing something (sorry, but this is in part Greek to me) or should the theme be expanded?

Many thanks for your help.

**Comment by ousia** [comment]
Closing the issue myself after discovering https://github.com/pages-themes/architect.

**Comment by jasonlong** [comment]
Perfect, was just going to point to that. 😸
